### ISSUE TITLE
Pull Requestに出ている×マークについて

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT/remote_monitor#9]
現在Travisを通す作業を行っています.
Pull Requestにおいては,Travisの監視下に置くと自動でTravisのチェックが入ります．
現在はTravisの設定ファイルを置いていないので×マークが出ますが,気にせず作業してください．
作業修了次第またお知らせします.

**Comment by forno** [comment]
念の為報告: 全ての作業が統合され、masterだけになりました。

**Comment by RyodoTanaka** [comment]
@forno 
報告ありがとうございます．
現在#9のPRの認証待ちです．mergeされ次第，issueを閉じます．

**Comment by RyodoTanaka** [comment]
@CIR-KIT/advent-calender-2016 
mergeが完了したので閉じます．
今後はlaunchだけテストするようになります．
新たなlaunchファイルを作成した場合には，新たにテスト用launchを作成する必要があります．
